language: ruby
rvm:
- 1.9.3

# If it builds, we're good
script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site --disable_external # Check validity, but if the link hasn't even has DSN records set, then it doesn't make sense to try and resolve

# after_success:
# - ruby deploy.rb

branches:
  only:
  - gh-pages

env:
  global:
    secure: bXRAJVuuZ2QxVODaw0Vvyqeqs1uz9fJPsD0yrtVvxpdXAhbNRIqSB/jVYAcHbtf3JqvQ6Z8B4EsaAGMJO4VoYdKwO297QPyT4Qb5oeLKM24v7c6eMjddp4hYi6pBNqUTNEG2n/hYEBfX/5lN4/h6p5913onD1+9245PGn5vbBPs=
